// <auto-generated />
namespace Craft.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class keyaddedinDistributor_Bar : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(keyaddedinDistributor_Bar));
        
        string IMigrationMetadata.Id
        {
            get { return "201803131233553_key added in Distributor_Bar"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
