// <auto-generated />
namespace Craft.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addeddistributor_beertable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addeddistributor_beertable));
        
        string IMigrationMetadata.Id
        {
            get { return "201803091607163_added distributor_beer table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
